# Change these first
owner: Kaisbn # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Authentication
    url: https://auth.kaisbn.fr
  - name: Traefik NAS
    url: https://nas.kaisbn.fr
  - name: Traefik RPi
    url: https://rpi.kaisbn.fr
  - name: Home assistant
    url: https://home.kaisbn.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kaisbn.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HomeLab
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime data and status page for hosted services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
